# Generated by Django 6.0.2 on 2026-02-25 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('Happiness', 'Happiness'), ('Sadness', 'Sadness'), ('Fear', 'Fear'), ('Anger', 'Anger'), ('Anxiety', 'Anxiety'), ('Neutral', 'Neutral')], max_length=20)),
                ('confidence', models.FloatField(help_text='Prediction confidence between 0 and 1.')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='dummy-v1', max_length=50)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_result', to='monitor.journalentry')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
