# Generated by Django 5.2.11 on 2026-02-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionresult',
            name='emotion',
            field=models.CharField(choices=[('joy_excitement', 'Joy & Excitement'), ('affection', 'Affection'), ('anger_disgust', 'Anger & Disgust'), ('sadness_grief', 'Sadness & Grief'), ('fear_nervousness', 'Fear & Nervousness'), ('cognitive', 'Cognitive (Curiosity/Surprise)'), ('neutral', 'Neutral')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='model_version',
            field=models.CharField(default='roberta-v1', max_length=50),
        ),
    ]
